#!/usr/bin/env bash
set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# source debconf library
. /usr/share/debconf/confmodule

case "$1" in
    configure)
        setcap cap_net_raw+eip /usr/bin/bootstrapper
        mkdir -p /etc/scion/certs
        chown scion:scion -R /etc/scion/certs
        if [ ! -f /.dockerenv ]; then
            systemctl daemon-reload > /dev/null 2>&1
        fi

        status=0
        # retrieve the first active network interface
        iface=$(ip -oneline address show up | awk '/inet.*brd/{print $2; exit}') || status=$?
        if [ $status -ne 0 ] || [ -z "$iface" ]; then
            echo "[x] Could not find an active network interface, manual systemd startup needed"
            exit 0
        else
            echo "[*] Using $iface to bootstrap SCION endhost ..."
        fi

        if [ ! -f /.dockerenv ]; then
            systemctl enable --now scion-bootstrapper@"$iface".service > /dev/null 2>&1 || status=$?
            systemctl restart --now scion-daemon.service > /dev/null 2>&1 || true
        else
            # In a docker environment, run directly
            /usr/bin/bootstrapper -iface "$iface" -config /etc/scion/bootstrapper.toml || status=$?
        fi
        if [ $status -ne 0 ]; then
            if [ ! -f /.dockerenv ]; then
                journalctl _SYSTEMD_INVOCATION_ID="$(systemctl show --value -p InvocationID scion-bootstrapper@ens3.service)" | awk 'BEGIN {FS="lvl=eror "} ; /lvl=eror msg=".*/{print "\t"$2;}' || true
            fi
            echo "[x] Could not bootstrap SCION configuration in the current network, no SCION support available or manual configuration needed."
        else
            echo "[*] ... and completed SCION endhost configuration successfully. Please start scion-dispatcher where required."
        fi
        exit 0
        ;;
    abort-*)
        # How'd we get here??
        exit 1
        ;;
    *)
        ;;
esac

