name: master

on: [push]

env:
  timeout: 10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install build requirements
        run: |
          sudo apt-get update
          sudo apt-get install build-essential rpm python3 -y
      - name: Build with make
        timeout-minutes: ${{ fromJSON(env.timeout) }}
        run: make build
      - name: Check output
        run: ls -a ./scion-bootstrapper ./bin/
      - name: Check help
        run: ./scion-bootstrapper --help

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Print environment
        run: cmd.exe /K set
      - name: Print environment
        run: gci env:* | sort-object name
      - name: Build with make
        timeout-minutes: ${{ fromJSON(env.timeout) }}
        run: make.exe bootstrapper
      - name: Check output
        run: dir scion-bootstrapper.exe
      - name: Check help
        run: scion-bootstrapper.exe --help

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Print environment
        run: env
      - name: Build with make
        timeout-minutes: ${{ fromJSON(env.timeout) }}
        run: make bootstrapper
      - name: Check output
        run: ls -a ./scion-bootstrapper ./bin/
      - name: Check help
        run: ./scion-bootstrapper --help
